# Generated by Django 4.2 on 2023-12-27 19:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0007_reserve_alter_file_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name=' التصنيف')),
            ],
            options={
                'verbose_name': '   تصنيف',
                'verbose_name_plural': '  تصنيف المنتجات ',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name=' الاسم')),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True, verbose_name='  الفون')),
                ('national_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='  رقم البطاقة ')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ الاضافة')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='  ملاحظات ')),
                ('file', models.FileField(blank=True, null=True, upload_to='client_files/', verbose_name='  ملف')),
            ],
            options={
                'verbose_name': '   عميل',
                'verbose_name_plural': '  العملاء ',
            },
        ),
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 27, 21, 26, 33, 411240), null=True, verbose_name=' تاريخ الاضافة')),
                ('deposite_months', models.IntegerField(blank=True, default=0, null=True, verbose_name=' عدد الاقساط ')),
                ('first_paid', models.IntegerField(blank=True, default=0, null=True, verbose_name='  المقدم ')),
                ('total_paid', models.IntegerField(blank=True, default=0, null=True, verbose_name='  مجموع المدفوع حتى الان ')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.client', verbose_name=' العميل')),
            ],
            options={
                'verbose_name': '   فاتورة',
                'verbose_name_plural': '  الفواتير',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name=' الاسم')),
                ('serial', models.CharField(blank=True, max_length=14, null=True, verbose_name='  رقم المسلسل')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='  ملاحظات ')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ الاضافة')),
                ('native_price', models.IntegerField(blank=True, default=1, null=True, verbose_name='السعر الاصلى ')),
                ('sell_price', models.IntegerField(blank=True, default=1, null=True, verbose_name=' سعر البيع ')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.category', verbose_name=' التصنيف')),
            ],
            options={
                'verbose_name': '   منتج',
                'verbose_name_plural': '  المنتجات ',
            },
        ),
        migrations.CreateModel(
            name='SellOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True, verbose_name='  الكمية')),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 27, 21, 26, 33, 411240), null=True, verbose_name=' تاريخ العملية')),
                ('sell_type', models.CharField(blank=True, choices=[('C', 'كاش'), ('D', 'قسط')], default='C', max_length=10, null=True, verbose_name='  طريقة الدفع')),
                ('added_value_for_deposite', models.IntegerField(blank=True, default=0, null=True, verbose_name=' القيمة المضافة')),
                ('pill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.pill', verbose_name=' العميل')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.product', verbose_name=' المنتج')),
            ],
            options={
                'verbose_name': '   عملية',
                'verbose_name_plural': '  عمليات البيع',
            },
        ),
        migrations.RemoveField(
            model_name='cost',
            name='session',
        ),
        migrations.RemoveField(
            model_name='file',
            name='session',
        ),
        migrations.RemoveField(
            model_name='medicin',
            name='session',
        ),
        migrations.DeleteModel(
            name='Reserve',
        ),
        migrations.RemoveField(
            model_name='session',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='paid',
            name='session',
        ),
        migrations.AlterField(
            model_name='paid',
            name='paid',
            field=models.IntegerField(blank=True, null=True, verbose_name=' المدفوع'),
        ),
        migrations.DeleteModel(
            name='Cost',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Medicin',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.AddField(
            model_name='paid',
            name='pill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.pill', verbose_name=' الفاتورة'),
        ),
    ]
