# Generated by Django 4.2.4 on 2024-01-17 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0008_category_client_pill_product_selloperation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paid',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 17, 13, 45, 0, 297307), null=True, verbose_name=' تاريخ الدفع'),
        ),
        migrations.AlterField(
            model_name='pill',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 17, 13, 45, 0, 296312), null=True, verbose_name=' تاريخ الاضافة'),
        ),
        migrations.AlterField(
            model_name='pill',
            name='total_paid',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=' مجموع المدفوع حتى الان '),
        ),
        migrations.AlterField(
            model_name='selloperation',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 17, 13, 45, 0, 297307), null=True, verbose_name=' تاريخ العملية'),
        ),
    ]
