# Generated by Django 4.2.4 on 2024-01-18 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0012_alter_selloperation_sell_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=' اسم المعاق'),
        ),
        migrations.AddField(
            model_name='car',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='  رقم التليفون'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=' اسم العميل'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='  رقم التليفون'),
        ),
        migrations.AlterField(
            model_name='selloperation',
            name='sell_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 18, 10, 2, 3, 525494), null=True, verbose_name=' تاريخ الخروج'),
        ),
    ]
