# Generated by Django 4.2.4 on 2024-01-19 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0013_car_name_car_phone_number_alter_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='  رقم التليفون'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='  رقم التليفون'),
        ),
        migrations.AlterField(
            model_name='selloperation',
            name='sell_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 19, 16, 19, 53, 566229), null=True, verbose_name=' تاريخ الخروج'),
        ),
    ]
