# Generated by Django 4.2.4 on 2024-01-19 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0014_alter_car_phone_number_alter_client_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selloperation',
            name='sell_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 19, 16, 55, 19, 679198), null=True, verbose_name=' تاريخ الخروج'),
        ),
    ]
